--- 
- 
  hosts: all
  remote_user: root
- name: Authenticate to CLoud 
  os_auth: 
    auth: 
      auth_url: "http://10.69.6.86:5000/v2.0"
      password: demo123
      project_name: demo
      username: demo
- name: Create a demo NFVi Stack
  os_stack: 
    name: "{{ demo }}"
    template: /home/heat-admin/stack_template_xl_demo_redhat.yaml

