--- 
- hosts: all
  remote_user: root
  tasks:
      - name: Set necessary authentication variables
        set_fact:
          os_auth:
          auth_type: password
          auth_url: "http://10.69.6.86:5000/v2.0"
          password: demo123
          project_name: demo
          username: demo

      - name: Launch a Heat stack
        os_stack:
          auth: "{{ os_auth }}"
          name: "demo_stack"
          template: "/root/stack_template_xl_demo_redhat.yaml"
